$WORKDIR/INTC_files/rtl_src/spl2/memory/sim_sp_mem.v
$WORKDIR/INTC_files/rtl_src/spl2/memory/sim_sdp_mem.v
$WORKDIR/INTC_files/rtl_src/spl2/memory/spl_pt_mem.v
$WORKDIR/INTC_files/rtl_src/spl2/fifo/sim_fifo.v
$WORKDIR/INTC_files/rtl_src/spl2/fifo/spl_fifo.v
$WORKDIR/INTC_files/rtl_src/spl2/spl_inc.v
$WORKDIR/INTC_files/rtl_src/spl2/spl_cci.v
$WORKDIR/INTC_files/rtl_src/spl2/spl_csr.v
$WORKDIR/INTC_files/rtl_src/spl2/spl_core.v
$WORKDIR/INTC_files/rtl_src/spl2/spl_cci_top.v
$WORKDIR/INTC_files/rtl_src/afu2/afu_top.v
$WORKDIR/INTC_files/rtl_src/afu2/afu_csr.v
$WORKDIR/INTC_files/rtl_src/afu2/afu_io.v
$WORKDIR/INTC_files/rtl_src/afu2/afu_core.v
